// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function GetConnectionInfo():Promise<port.ConnectionInfo>;

export function IsServerRunning():Promise<boolean>;

export function StartServer(arg1:number):Promise<port.ConnectionInfo>;

export function StopServer():Promise<void>;
