// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionInfo() {
  return window['go']['main']['App']['GetConnectionInfo']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
